AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
